# Auto-generated by Cloud AI Agent
FROM private-registry.sohucs.com/domeos-pub/node:22.14.0-alpine3.21

WORKDIR /app

# Configure npm proxy
RUN npm config set proxy http://10.18.34.194:3128 && npm config set https-proxy http://10.18.34.194:3128

# Install git client
RUN apk add --no-cache git

# Install pi packages
RUN npm init -y && npm install --ignore-scripts @earendil-works/pi-agent-core @earendil-works/pi-ai express

# Copy skills, prompts, and extensions
{{if .SkillsDir}}COPY {{.SkillsDir}}/ ./pi-skills/{{end}}
{{if .PromptsDir}}COPY {{.PromptsDir}}/ ./pi-prompts/{{end}}
{{if .ExtensionsDir}}COPY {{.ExtensionsDir}}/ ./extensions/{{end}}

# Copy HTTP wrapper
COPY {{.WrapperScript}} ./server.js
{{if .McpClient}}COPY {{.McpClient}} ./mcp-client.js{{end}}

# Work directory for code repos and logs (mounted at runtime)
RUN mkdir -p /workspace /logs

{{if .CustomContent}}{{.CustomContent}}{{end}}

EXPOSE {{.ExposePort}}

CMD ["node", "server.js"]
