# Auto-generated by Cloud AI Agent - Team Mode
FROM private-registry.sohucs.com/domeos-pub/node:22.14.0-alpine3.21

WORKDIR /app

# Configure npm proxy
RUN npm config set proxy http://10.18.34.194:3128 && npm config set https-proxy http://10.18.34.194:3128

# Install pi packages
RUN npm init -y && npm install --ignore-scripts @earendil-works/pi-agent-core @earendil-works/pi-ai express

# Copy team manifest
COPY team-manifest.json ./

# Copy team wrapper as server.js
COPY team-server.js ./server.js
{{if .McpClient}}COPY {{.McpClient}} ./mcp-client.js{{end}}
{{if .LLMLogger}}COPY {{.LLMLogger}} ./llm-logger.js{{end}}

# Copy each agent's directory
{{range .AgentDirs}}COPY {{.}}/ ./{{.}}/
{{end}}
# Copy team-level prompts and skills
{{if .TeamPromptsDir}}COPY {{.TeamPromptsDir}}/ ./team-prompts/{{end}}
{{if .TeamSkillsDir}}COPY {{.TeamSkillsDir}}/ ./team-skills/{{end}}

# Work directory for code repos and logs (mounted at runtime)
RUN mkdir -p /workspace /logs

{{if .CustomContent}}{{.CustomContent}}{{end}}

EXPOSE {{.ExposePort}}

CMD ["node", "server.js"]
