package codegen

// AgentType constants for template type selection.
const (
	AgentTypePI         = "pi"
	AgentTypeClaudeCode = "claude-code"
	AgentTypeCodex      = "codex"
)

// GenerateDockerfileByAgentType generates a Dockerfile for the given agent type.
// Falls back to the default PI Dockerfile if the type is empty or unknown.
func GenerateDockerfileByAgentType(agentType string, data *DockerfileData) (string, error) {
	// Set defaults
	if data.NodeVersion == "" {
		data.NodeVersion = "22"
	}
	if data.WrapperScript == "" {
		data.WrapperScript = "server.js"
	}
	if data.McpClient == "" {
		data.McpClient = "mcp-client.js"
	}
	if data.SkillsDir == "" {
		data.SkillsDir = "pi-skills"
	}
	if data.PromptsDir == "" {
		data.PromptsDir = "pi-prompts"
	}
	if data.ExtensionsDir == "" {
		data.ExtensionsDir = "extensions"
	}
	if data.ExposePort == 0 {
		data.ExposePort = 3000
	}

	// If the user provided custom content, render it directly.
	if data.CustomContent != "" {
		return generateFromTemplate(data.CustomContent, data)
	}

	name := agentType
	if name == "" {
		name = AgentTypePI
	}

	tmpl, err := getTemplate(name)
	if err != nil {
		return "", err
	}
	return generateFromTemplate(tmpl, data)
}

// ---- Built-in fallback templates (used when external files are unavailable) ----

const defaultDockerfilePI = `# Auto-generated by Cloud AI Agent
FROM private-registry.sohucs.com/domeos-pub/node:22.14.0-alpine3.21

WORKDIR /app

# Configure npm proxy
RUN npm config set proxy http://10.18.34.194:3128 && npm config set https-proxy http://10.18.34.194:3128

# Install pi packages
RUN npm init -y && npm install --ignore-scripts @earendil-works/pi-agent-core @earendil-works/pi-ai express

# Copy skills, prompts, and extensions
{{if .SkillsDir}}COPY {{.SkillsDir}}/ ./pi-skills/{{end}}
{{if .PromptsDir}}COPY {{.PromptsDir}}/ ./pi-prompts/{{end}}
{{if .ExtensionsDir}}COPY {{.ExtensionsDir}}/ ./extensions/{{end}}

# Copy HTTP wrapper
COPY {{.WrapperScript}} ./server.js
{{if .McpClient}}COPY {{.McpClient}} ./mcp-client.js{{end}}

# Work directory for code repos (bind-mounted at runtime)
RUN mkdir -p /workspace /logs

{{if .CustomContent}}{{.CustomContent}}{{end}}

EXPOSE {{.ExposePort}}

CMD ["node", "server.js"]
`

const defaultDockerfileClaudeCode = `# Auto-generated by Cloud AI Agent - Claude Code
FROM private-registry.sohucs.com/domeos-pub/node:22.14.0-alpine3.21

WORKDIR /app

# Configure npm proxy
RUN npm config set proxy http://10.18.34.194:3128 && npm config set https-proxy http://10.18.34.194:3128

# Install Claude Code packages
RUN npm init -y && npm install --ignore-scripts @anthropic-ai/sdk express

# Copy skills, prompts, and extensions
{{if .SkillsDir}}COPY {{.SkillsDir}}/ ./skills/{{end}}
{{if .PromptsDir}}COPY {{.PromptsDir}}/ ./prompts/{{end}}
{{if .ExtensionsDir}}COPY {{.ExtensionsDir}}/ ./extensions/{{end}}

# Copy HTTP wrapper
COPY {{.WrapperScript}} ./server.js
{{if .McpClient}}COPY {{.McpClient}} ./mcp-client.js{{end}}

# Work directory for code repos (bind-mounted at runtime)
RUN mkdir -p /workspace /logs

{{if .CustomContent}}{{.CustomContent}}{{end}}

EXPOSE {{.ExposePort}}

CMD ["node", "server.js"]
`

const defaultDockerfileCodex = `# Auto-generated by Cloud AI Agent - Codex
FROM private-registry.sohucs.com/domeos-pub/node:22.14.0-alpine3.21

WORKDIR /app

# Configure npm proxy
RUN npm config set proxy http://10.18.34.194:3128 && npm config set https-proxy http://10.18.34.194:3128

# Install Codex packages
RUN npm init -y && npm install --ignore-scripts @modelcontextprotocol/sdk openai express

# Copy skills, prompts, and extensions
{{if .SkillsDir}}COPY {{.SkillsDir}}/ ./skills/{{end}}
{{if .PromptsDir}}COPY {{.PromptsDir}}/ ./prompts/{{end}}
{{if .ExtensionsDir}}COPY {{.ExtensionsDir}}/ ./extensions/{{end}}

# Copy HTTP wrapper
COPY {{.WrapperScript}} ./server.js
{{if .McpClient}}COPY {{.McpClient}} ./mcp-client.js{{end}}

# Work directory for code repos (bind-mounted at runtime)
RUN mkdir -p /workspace /logs

{{if .CustomContent}}{{.CustomContent}}{{end}}

EXPOSE {{.ExposePort}}

CMD ["node", "server.js"]
`

const defaultDockerfileTeam = `# Auto-generated by Cloud AI Agent - Team Mode
FROM private-registry.sohucs.com/domeos-pub/node:22.14.0-alpine3.21

WORKDIR /app

# Configure npm proxy
RUN npm config set proxy http://10.18.34.194:3128 && npm config set https-proxy http://10.18.34.194:3128

# Install pi packages
RUN npm init -y && npm install --ignore-scripts @earendil-works/pi-agent-core @earendil-works/pi-ai express

# Copy team manifest
COPY team-manifest.json ./

# Copy team wrapper as server.js
COPY team-server.js ./server.js
{{if .McpClient}}COPY {{.McpClient}} ./mcp-client.js{{end}}

# Copy each agent's directory
{{range .AgentDirs}}COPY {{.}}/ ./{{.}}/
{{end}}
# Copy team-level prompts and skills
{{if .TeamPromptsDir}}COPY {{.TeamPromptsDir}}/ ./team-prompts/{{end}}
{{if .TeamSkillsDir}}COPY {{.TeamSkillsDir}}/ ./team-skills/{{end}}

# Work directory for code repos (bind-mounted at runtime)
RUN mkdir -p /workspace /logs

{{if .CustomContent}}{{.CustomContent}}{{end}}

EXPOSE {{.ExposePort}}

CMD ["node", "server.js"]
`
