package codegen

import (
	"bytes"
	"text/template"
)

type DockerfileData struct {
	NodeVersion   string
	SkillsDir     string
	PromptsDir    string
	ExtensionsDir string
	WrapperScript string
	ExposePort    int
	CustomContent string
}

const defaultDockerfile = `# Auto-generated by Cloud AI Agent
FROM node:{{.NodeVersion}}-alpine

WORKDIR /app

# Install pi packages
RUN npm init -y && npm install --ignore-scripts @earendil-works/pi-agent-core @earendil-works/pi-ai express

# Copy skills, prompts, and extensions
{{if .SkillsDir}}COPY {{.SkillsDir}}/ ./pi-skills/{{end}}
{{if .PromptsDir}}COPY {{.PromptsDir}}/ ./pi-prompts/{{end}}
{{if .ExtensionsDir}}COPY {{.ExtensionsDir}}/ ./extensions/{{end}}

# Copy HTTP wrapper
COPY {{.WrapperScript}} ./server.js

# Work directory for code repos (bind-mounted at runtime)
RUN mkdir -p /workspace

{{if .CustomContent}}{{.CustomContent}}{{end}}

EXPOSE {{.ExposePort}}

CMD ["node", "server.js"]
`

func GenerateDockerfile(data *DockerfileData) (string, error) {
	if data.NodeVersion == "" {
		data.NodeVersion = "22"
	}
	if data.WrapperScript == "" {
		data.WrapperScript = "server.js"
	}
	if data.SkillsDir == "" {
		data.SkillsDir = "pi-skills"
	}
	if data.PromptsDir == "" {
		data.PromptsDir = "pi-prompts"
	}
	if data.ExtensionsDir == "" {
		data.ExtensionsDir = "extensions"
	}
	if data.ExposePort == 0 {
		data.ExposePort = 3000
	}

	tmpl := data.CustomContent
	if tmpl == "" {
		tmpl = defaultDockerfile
	}

	t, err := template.New("Dockerfile").Parse(tmpl)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
