package codegen

import (
	"bytes"
	"text/template"
)

// AgentType constants for template type selection.
const (
	AgentTypePI         = "pi"
	AgentTypeClaudeCode = "claude-code"
	AgentTypeCodex      = "codex"
)

// defaultDockerfileClaudeCode is the Dockerfile template for Claude Code agents.
const defaultDockerfileClaudeCode = `# Auto-generated by Cloud AI Agent - Claude Code
FROM private-registry.sohucs.com/domeos-pub/node:22.14.0-alpine3.21

WORKDIR /app

# Configure npm proxy
RUN npm config set proxy http://10.18.34.194:3128 && npm config set https-proxy http://10.18.34.194:3128

# Install Claude Code packages
RUN npm init -y && npm install --ignore-scripts @anthropic-ai/claude-code-sdk express

# Copy skills, prompts, and extensions
{{if .SkillsDir}}COPY {{.SkillsDir}}/ ./skills/{{end}}
{{if .PromptsDir}}COPY {{.PromptsDir}}/ ./prompts/{{end}}
{{if .ExtensionsDir}}COPY {{.ExtensionsDir}}/ ./extensions/{{end}}

# Copy HTTP wrapper
COPY {{.WrapperScript}} ./server.js
{{if .McpClient}}COPY {{.McpClient}} ./mcp-client.js{{end}}

# Work directory for code repos (bind-mounted at runtime)
RUN mkdir -p /workspace

{{if .CustomContent}}{{.CustomContent}}{{end}}

EXPOSE {{.ExposePort}}

CMD ["node", "server.js"]
`

// defaultDockerfileCodex is the Dockerfile template for Codex agents.
const defaultDockerfileCodex = `# Auto-generated by Cloud AI Agent - Codex
FROM private-registry.sohucs.com/domeos-pub/node:22.14.0-alpine3.21

WORKDIR /app

# Configure npm proxy
RUN npm config set proxy http://10.18.34.194:3128 && npm config set https-proxy http://10.18.34.194:3128

# Install Codex packages
RUN npm init -y && npm install --ignore-scripts @modelcontextprotocol/sdk openai express

# Copy skills, prompts, and extensions
{{if .SkillsDir}}COPY {{.SkillsDir}}/ ./skills/{{end}}
{{if .PromptsDir}}COPY {{.PromptsDir}}/ ./prompts/{{end}}
{{if .ExtensionsDir}}COPY {{.ExtensionsDir}}/ ./extensions/{{end}}

# Copy HTTP wrapper
COPY {{.WrapperScript}} ./server.js
{{if .McpClient}}COPY {{.McpClient}} ./mcp-client.js{{end}}

# Work directory for code repos (bind-mounted at runtime)
RUN mkdir -p /workspace

{{if .CustomContent}}{{.CustomContent}}{{end}}

EXPOSE {{.ExposePort}}

CMD ["node", "server.js"]
`

// generateFromTemplate renders a Dockerfile from the given template string and data.
func generateFromTemplate(tmpl string, data *DockerfileData) (string, error) {
	t, err := template.New("Dockerfile").Parse(tmpl)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// GenerateDockerfileByAgentType generates a Dockerfile for the given agent type.
// Falls back to the default PI Dockerfile if the type is empty or unknown.
func GenerateDockerfileByAgentType(agentType string, data *DockerfileData) (string, error) {
	// Set defaults
	if data.NodeVersion == "" {
		data.NodeVersion = "22"
	}
	if data.WrapperScript == "" {
		data.WrapperScript = "server.js"
	}
	if data.McpClient == "" {
		data.McpClient = "mcp-client.js"
	}
	if data.SkillsDir == "" {
		data.SkillsDir = "pi-skills"
	}
	if data.PromptsDir == "" {
		data.PromptsDir = "pi-prompts"
	}
	if data.ExtensionsDir == "" {
		data.ExtensionsDir = "extensions"
	}
	if data.ExposePort == 0 {
		data.ExposePort = 3000
	}

	// If the user provided custom content, always use it.
	if data.CustomContent != "" {
		return GenerateDockerfile(data)
	}

	switch agentType {
	case AgentTypeClaudeCode:
		return generateFromTemplate(defaultDockerfileClaudeCode, data)
	case AgentTypeCodex:
		return generateFromTemplate(defaultDockerfileCodex, data)
	default:
		return GenerateDockerfile(data)
	}
}