package codegen

import (
	"bytes"
	"text/template"
)

type TeamDockerfileData struct {
	AgentDirs     []string
	TeamPromptsDir  string
	TeamSkillsDir   string
	McpClient       string
	ExposePort      int
	CustomContent string
}

const teamDockerfileTmpl = `# Auto-generated by Cloud AI Agent - Team Mode
FROM private-registry.sohucs.com/domeos-pub/node:22.14.0-alpine3.21

WORKDIR /app

# Configure npm proxy
RUN npm config set proxy http://10.18.34.194:3128 && npm config set https-proxy http://10.18.34.194:3128

# Install pi packages
RUN npm init -y && npm install --ignore-scripts @earendil-works/pi-agent-core @earendil-works/pi-ai express

# Copy team manifest
COPY team-manifest.json ./

# Copy team wrapper as server.js
COPY team-server.js ./server.js
{{if .McpClient}}COPY {{.McpClient}} ./mcp-client.js{{end}}

# Copy each agent's directory
{{range .AgentDirs}}COPY {{.}}/ ./{{.}}/
{{end}}
# Copy team-level prompts and skills
{{if .TeamPromptsDir}}COPY {{.TeamPromptsDir}}/ ./team-prompts/{{end}}
{{if .TeamSkillsDir}}COPY {{.TeamSkillsDir}}/ ./team-skills/{{end}}

# Work directory for code repos (bind-mounted at runtime)
RUN mkdir -p /workspace

{{if .CustomContent}}{{.CustomContent}}{{end}}

EXPOSE {{.ExposePort}}

CMD ["node", "server.js"]
`

func GenerateTeamDockerfile(data *TeamDockerfileData) (string, error) {
	if data.McpClient == "" {
		data.McpClient = "mcp-client.js"
	}
	if data.ExposePort == 0 {
		data.ExposePort = 3000
	}

	tmpl := data.CustomContent
	if tmpl == "" {
		tmpl = teamDockerfileTmpl
	}

	t, err := template.New("TeamDockerfile").Parse(tmpl)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}
